# NeoForge Mod Configuration
# Based on BuffMobs Fabric mod
# Documentation: https://docs.neoforged.net/docs/gettingstarted/modfiles/

modLoader="javafml"
loaderVersion="[4,)"
license="MIT"
issueTrackerURL="https://github.com/Khotyz/BuffMobs/issues"

[[mods]]
modId="buffmobs"
version="${mod_version}"
displayName="BuffMobs"
displayURL="https://github.com/Khotyz/BuffMobs"
logoFile="assets/buffmobs/icon.png"
credits="khotyz"
authors="khotyz"
description='''
A mod that buffs hostile mobs based on configurable settings
'''

[[dependencies.buffmobs]]
modId="neoforge"
type="required"
versionRange="[21.10,)"
ordering="NONE"
side="BOTH"

[[dependencies.buffmobs]]
modId="minecraft"
type="required"
versionRange="[1.21.10]"
ordering="NONE"
side="BOTH"